-- MySQL Script generated by MySQL Workbench
-- Wed Sep 15 17:42:12 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rockola
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rockola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rockola` DEFAULT CHARACTER SET utf8 ;
USE `rockola` ;

-- -----------------------------------------------------
-- Table `rockola`.`Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rockola`.`Pais` (
  `cod_nacionalidad` INT NOT NULL AUTO_INCREMENT,
  `nom_nacionalidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_nacionalidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rockola`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rockola`.`USUARIO` (
  `cod_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellios` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(2) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `cod_nacionalidad` INT NOT NULL,
  PRIMARY KEY (`cod_usuario`),
  INDEX `cod_nacionalidad_idx` (`cod_nacionalidad` ASC) VISIBLE,
  CONSTRAINT `cod_nacionalidad`
    FOREIGN KEY (`cod_nacionalidad`)
    REFERENCES `rockola`.`Pais` (`cod_nacionalidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rockola`.`Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rockola`.`Genero` (
  `cod_genero` INT NOT NULL AUTO_INCREMENT,
  `Nom_genero` VARCHAR(35) NULL,
  PRIMARY KEY (`cod_genero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rockola`.`Artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rockola`.`Artista` (
  `cod_artista` INT NOT NULL AUTO_INCREMENT,
  `nom_artista` VARCHAR(45) NOT NULL,
  `cod_nacionalidad` INT NOT NULL,
  PRIMARY KEY (`cod_artista`),
  INDEX `cod_nacionalidad_idx` (`cod_nacionalidad` ASC) VISIBLE,
  CONSTRAINT `cod_nacionalidad_fk`
    FOREIGN KEY (`cod_nacionalidad`)
    REFERENCES `rockola`.`Pais` (`cod_nacionalidad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rockola`.`Cancion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rockola`.`Cancion` (
  `cod_cancion` INT NOT NULL AUTO_INCREMENT,
  `nom_cancion` VARCHAR(45) NOT NULL,
  `codi_artista` INT NOT NULL,
  `codi_genero` INT NOT NULL,
  PRIMARY KEY (`cod_cancion`),
  INDEX `cod_artista_idx` (`codi_artista` ASC) VISIBLE,
  INDEX `cod_genero_idx` (`codi_genero` ASC) VISIBLE,
  CONSTRAINT `cod_artista`
    FOREIGN KEY (`codi_artista`)
    REFERENCES `rockola`.`Artista` (`cod_artista`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cod_genero`
    FOREIGN KEY (`codi_genero`)
    REFERENCES `rockola`.`Genero` (`cod_genero`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
